#Using "Prefix + $" to rename the session
set -g base-index 1
set -g pane-base-index 1

set-option -g allow-rename off

# True colors mode
# Add truecolor support
set-option -ga terminal-overrides ",*:Tc"
# Default terminal is 256 colors
set -g default-terminal "screen-256color"

# Statusbar has white on black/transparent background
set -g status-bg "#292d3e"
set -g status-fg "#bfc0c5"

#set -g @online_icon "ON"
#set -g @offline_icon "OFF"
set -g set-titles on
set -g status-right-length 65
set -g status-left-length 15
set -g status-right "%a %R %b %d"

setw -g window-status-format "[#I #W]"
setw -g window-status-current-format "[#I* #W]"
#setw -g window-status-current-style fg=black,bg="#2596be"
#setw -g status-style fg="#eab676" bg ="#154c79"
# Remap prefix to C-a
set -g prefix C-a
bind C-a send-prefix
unbind C-b

unbind r
bind r source-file ~/.tmux.conf

# Keymap
bind \\ split-window -h -c '#{pane_current_path}'
bind \/ split-window -v -c '#{pane_current_path}'
unbind '"'
unbind %

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

bind J resize-pane -D 10
bind K resize-pane -U 10
bind L resize-pane -L 10
bind H resize-pane -R 10

bind -r m resize-pane -Z

set-window-option -g mode-keys vi

bind-key -T copy-mode-vi 'v' send -X begin-selection # start selecting text with "v"
bind-key -T copy-mode-vi 'y' send -X copy-selection # copy text with "y"

# Use vim keybindings in copy mode
set-window-option -g mode-keys vi

bind-key -T copy-mode-vi 'v' send -X begin-selection # start selecting text with "v"
bind-key -T copy-mode-vi 'y' send -X copy-selection # copy text with "y"

## set the default TERM
set -g default-terminal screen

## update the TERM variable of terminal emulator when creating a new session or attaching a existing session
set -g update-environment 'DISPLAY SSH_ASKPASS SSH_AGENT_PID SSH_CONNECTION WINDOWID XAUTHORITY TERM'
## determine if we should enable 256-colour support
if "[[ ${TERM} =~ 256color || ${TERM} == fbterm ]]" 'set -g default-terminal screen-256color'

# tpm plugin
set -g @plugin 'tmux-plugins/tpm'

# list of tmux plugins
set -g @plugin 'jimeh/tmux-themepack' # to configure tmux theme
set -g @plugin 'tmux-plugins/tmux-resurrect' # persist tmux sessions after computer restart
set -g @plugin 'tmux-plugins/tmux-continuum' # automatically saves sessions for you every 15 minutes

set -g @themepack 'powerline/default/cyan' # use this theme for tmux

set -g @resurrect-capture-pane-contents 'on' # allow tmux-ressurect to capture pane contents
set -g @continuum-restore 'on' # enable tmux-continuum functionality

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
