set -g default-terminal "screen-256color"
set -g prefix C-a
unbind C-b
bind-key C-a send prefix

unbind %
bind | split-window -h
unbind ""

bind - split-window -v
unbind r
bind r source-file ~/.tmux.conf

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
bind J resize-pane -D 10
bind K resize-pane -U 10
bind L resize-pane -L 10
bind H resize-pane -R 10

# keybind for maximizing and minimizing tmux pane
bind -r m resize-pane -Z

set -g extended-keys on
set -g mouse on

set-window-option -g mode-keys vi

bind-key -T copy-mode-vi 'v' send -x begin-selection # start selecting text with "v" 
bind-key -T copy-mode-vi 'C-v' send -X rectangle-toggle # start selecting text with "v"
bind-key -T copy-mode-vi 'y' send -X copy-selection # copy text with "y"
unbind -T copy-mode-vi MouseDragEnd1Pane # don't exit copy mode after dragging with mouse

# tpm plugin
set -g @plugin 'tmux-plugins/tpm'

# list of tux plugins
set -g @plugin 'christoomey/vim-tmux-navigator' # for navigating panes and vim/nvim with Ctrl-hjkl 
set -g @plugin 'jimeh/tmux-themepack' # to configure tmux theme 
set -g @plugin 'tmux-plugins/tmux-resurrect'# persist tux sessions after computer restart
set -g @plugin 'tux-plugins/tmux-continuum' # automatically saves sessions for you every 15 minutes

set -g @plugin 'nordtheme/tmux' # use this theme for tmux set -g @themepack 'basic'
set -g @themepack 'powerline/block/blue'
set -g @resurrect-capture pane-contents 'on' # allow tmux-ressurect to capture pane contents
set -g @continuum-restore 'on' # enable tux-continuum functionality

# Initialize TUX plugin manager (keep this line at the very bottom of tmux.conf)
run ~/.config/tmux/plugins/tpm/tpm/
